export const config = {
  title: "Mario Gomez | Notes",
  author: "Mario Gomez",
  headerTitle: "Mario Gomez",
  description: "Recent Notes",
  language: "en-us",
  theme: "system",
  siteUrl: "https://d3w287eijv5ek9.cloudfront.net",
  avatar: "/avatar.png",
  email: "mariogomezarr@gmail.com",
  github: "https://github.com/magomzr",
  linkedin: "https://www.linkedin.com/in/mariogomeza/",
  locale: "en-US",
  comments: {
    provider: "giscus",
    giscusConfig: {
      repo: "magomzr/discussions",
      repositoryId: "R_kgDONCSlzg",
      category: "General",
      categoryId: "DIC_kwDONCSlzs4Cjeyu",
      mapping: "pathname",
      reactions: "1",
      metadata: "0",
      theme: "light",
      darkTheme: "transparent_dark",
      themeURL: "",
      lang: "en",
    },
  },
  search: {
    provider: "kbar",
    kbarConfig: {
      searchDocumentsPath: "search.json",
    },
  },
};
